config/routes.rb
Ygit::Application.routes.draw do
  resources :sshkeys

  resources :repos

  root :to => "repos#index"

end

app/models/repo.rb
class Repo < ActiveRecord::Base

  validates :name, :format => { :with => /\A[a-zA-Z0-9_]+\Z/, :message => "must contain only letters and numbers" }, :length => { :minimum => 4 }

  before_validation(:on => :create) do
    self.name = name.downcase if attribute_present?("name")
  end

  def git_url
    "#{APP_CONFIG['repo_host']}/#{name}.git"
  end

  def full_repo_path
    "#{APP_CONFIG['repo_path']}/#{name}.git"
  end

  def get_files_raw
    `cd #{full_repo_path} && git ls-tree -l -t master`  
  end

  def get_files
    raw = get_files_raw
    files = []
    raw.each_line do |line|
      /^\d+\s+(\S+?)\s[\S]+?\s+(\S+?)\s+(\S+)$/.match(raw)
      files << 1
    end
  end

  before_create do
    system "[ ! -e #{full_repo_path} ]"
    if $?.to_i == 0 
      system "mkdir -p #{full_repo_path}"
      system "cd #{full_repo_path} && git --bare init"
    end
  end

  before_destroy do
    system "rm -rf #{full_repo_path}"
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_filter :authenticate

  # GET /repos
  # GET /repos.xml
  def index
    @repos = Repo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @repos }
    end
  end

  # GET /repos/1
  # GET /repos/1.xml
  def show
    @repo = Repo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @repo }
    end
  end

  # GET /repos/new
  # GET /repos/new.xml
  def new
    @repo = Repo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repo }
    end
  end

  # GET /repos/1/edit
  def edit
    @repo = Repo.find(params[:id])
  end

  # POST /repos
  # POST /repos.xml
  def create
    @repo = Repo.new(params[:repo])

    respond_to do |format|
      if @repo.save
        format.html { redirect_to(@repo, :notice => 'Repo was successfully created.') }
        format.xml  { render :xml => @repo, :status => :created, :location => @repo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @repo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repos/1
  # PUT /repos/1.xml
  def update
    @repo = Repo.find(params[:id])

    respond_to do |format|
      if @repo.update_attributes(params[:repo])
        format.html { redirect_to(@repo, :notice => 'Repo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.xml
  def destroy
    @repo = Repo.find(params[:id])
    @repo.destroy

    respond_to do |format|
      format.html { redirect_to(repos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= form_for(@repo, :html => { :class => "form-horizontal"}) do |f| %> 
  <fieldset>
    <legend></legend>
    
    <% if @repo.errors.any? %>
      <div id="error_explanation" class="alert alert-block alert-error fade in">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <h4 class="alert-heading"><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h4>
        <ul>
        <% @repo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <%= field_text(f, :name, :help => "lower case with no spaces")  %>
      <%= field_text_area(f, :description ) %>
      <%= field_text(f, :url, :class => "input-xlarge") %>

      <div class="form-actions">
        <%= f.submit :class => "btn btn-primary" %>
        <%= link_to 'Cancel', repos_path, :class => "btn"  %> 
      </div>

    </div>
  </fieldset>
<% end %>

app/views/repos/edit.html.erb
<h1><%= title "Edit #{@repo.name}" %></h1>

<%= render 'form' %>

app/views/repos/index.html.erb
<h1><%= title "Repositories" %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
  <% @repos.each do |repo| %>
    <tr>
      <td>
        <%= link_to repo.name, repo %>
      </td>
      <td>
        <%= link_to 'Edit', edit_repo_path(repo), :class => "btn btn-mini" %>
        <%= link_to 'Destroy', repo, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-mini btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to 'New Repo', new_repo_path, :class => "btn btn-primary" %>
</div>

app/views/repos/new.html.erb
<h1><%= title "New Repository" %></h1>

<%= render 'form' %>

app/views/repos/show.html.erb
<h2><%= title @repo.name %></h2>

<p>
  <%= @repo.description %>
</p>

<p>
  <b>Url:</b>
  <%= link_to @repo.url %>
</p>

<p>
  <b>Repo</b>
  <%= @repo.git_url %>
</p>

<p>
<pre><%=@repo.get_files_raw%></pre>
</p>

<div class="form-actions">
	<%= link_to 'Edit', edit_repo_path(@repo), :class => "btn" %>
	<%= link_to 'Back', repos_path, :class => "btn"  %> 
</div>