config/routes.rb
Ygit::Application.routes.draw do
  resources :sshkeys

  resources :repos

  root :to => "repos#index"

end

app/models/sshkey.rb
class Sshkey < ActiveRecord::Base
  validate :validate_key

  def validate_key
    sshkey_reg = /ssh-rsa\s+(\S+)\s(\S*)$/
    m = key.match(sshkey_reg)
    if !m
      errors.add(:key, 'Invalid')
      return
    end

    if name.empty?
      self.name=m[2]
    end
  end

  after_create :write_authorized_keys
  after_update :write_authorized_keys
  after_destroy :write_authorized_keys

  def write_authorized_keys 
    File.open("#{APP_CONFIG['authorized_keys_path']}/authorized_keys", 'w') do |file| 
      file.write(Sshkey.authorized_keys) 
    end
  end

  def self.authorized_keys
    "".tap do |result|
      Sshkey.all.each do |sskkey|
        result.concat "# --- #{sskkey.name}\n"
        result.concat "#{sskkey.key}\n"
      end
    end
  end
end

app/controllers/sshkeys_controller.rb
class SshkeysController < ApplicationController
  # GET /sshkeys
  # GET /sshkeys.xml
  def index
    @sshkeys = Sshkey.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sshkeys }
    end
  end

  # GET /sshkeys/1
  # GET /sshkeys/1.xml
  def show
    @sshkey = Sshkey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sshkey }
    end
  end

  # GET /sshkeys/new
  # GET /sshkeys/new.xml
  def new
    @sshkey = Sshkey.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sshkey }
    end
  end

  # GET /sshkeys/1/edit
  def edit
    @sshkey = Sshkey.find(params[:id])
  end

  # POST /sshkeys
  # POST /sshkeys.xml
  def create
    @sshkey = Sshkey.new(params[:sshkey])

    respond_to do |format|
      if @sshkey.save
        format.html { redirect_to(@sshkey, :notice => 'Sshkey was successfully created.') }
        format.xml  { render :xml => @sshkey, :status => :created, :location => @sshkey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sshkey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sshkeys/1
  # PUT /sshkeys/1.xml
  def update
    @sshkey = Sshkey.find(params[:id])

    respond_to do |format|
      if @sshkey.update_attributes(params[:sshkey])
        format.html { redirect_to(@sshkey, :notice => 'Sshkey was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sshkey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sshkeys/1
  # DELETE /sshkeys/1.xml
  def destroy
    @sshkey = Sshkey.find(params[:id])
    @sshkey.destroy

    respond_to do |format|
      format.html { redirect_to(sshkeys_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sshkeys_helper.rb
module SshkeysHelper
end

app/views/sshkeys/_form.html.erb
<%= form_for(@sshkey, :html => { :class => "form-horizontal"}) do |f| %>
  <fieldset>
    <legend></legend>

    <% if @sshkey.errors.any? %>
      <div id="error_explanation" class="alert alert-block alert-error fade in">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <h4 class="alert-heading"><%= pluralize(@sshkey.errors.count, "error") %> prohibited this sshkey from being saved:</h4>

        <ul>
        <% @sshkey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= field_text(f, :name) %>
    <%= field_text(f, :description) %>
    <%= field_text_area(f, :key, :rows => 6) %>

    <div class="form-actions">
      <%= f.submit :class => "btn btn-primary" %>
      <%= link_to 'Cancel', sshkeys_path, :class => "btn"  %> 
    </div>

  </fieldset>
<% end %>

app/views/sshkeys/edit.html.erb
<h1><%= title "Edit #{@sshkey.name}" %></h1>

<%= render 'form' %>

app/views/sshkeys/index.html.erb
<h1><%= title "SSH Keys" %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
  <% @sshkeys.each do |sshkey| %>
    <tr>
      <td><%= sshkey.name %></td>
      <td><%= sshkey.description %></td>
      <td>
        <%= link_to 'Show', sshkey, :class => "btn btn-mini" %>
        <%= link_to 'Edit', edit_sshkey_path(sshkey), :class => "btn btn-mini" %>
        <%= link_to 'Destroy', sshkey, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-mini btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to 'New SSH Key', new_sshkey_path, :class => "btn btn-primary"  %>
</div>

app/views/sshkeys/new.html.erb
<h1><%= title "New SSH Key" %></h1>

<%= render 'form' %>

app/views/sshkeys/show.html.erb
<% title @sshkey.name %>

<p>
  <b>Name:</b>
  <%= @sshkey.name %>
</p>

<p>
  <b>Description:</b>
  <%= @sshkey.description %>
</p>

<p>
  <pre><%= @sshkey.key %></pre>
</p>

<div class="form-actions">
  <%= link_to 'Edit', edit_sshkey_path(@sshkey), :class => "btn" %>
  <%= link_to 'Back', sshkeys_path, :class => "btn"  %> 
</div>