config/routes.rb
Ygit::Application.routes.draw do
  resources :sshkeys

  resources :repos

  root :to => "repos#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />  
  <!--[if IE]><![endif]-->  
  <title><%= title [APP_CONFIG['app_title']] %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= description %>
  <%= author %>
  <%= canonical %>
  <%= yield(:meta) %>
  <%= csrf_meta_tag %>
  
  <!-- Styles -->
  <%= stylesheet_link_tag "bootstrap.min" %>
  <style>
    body {
      padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
    }
  </style>
  <%= stylesheet_link_tag "bootstrap-responsive.min", "application" %>

  <%= yield(:css) %>
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->    
  
  <%= cdn_js "//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js", "window.jQuery", "/javascripts/jquery-1.7.1.min.js" %>
  
  <%= javascript_include_tag "jquery_ujs.js", "bootstrap", "application" %> 
  <%= yield(:javascript) %> 
</head>
<body id="<%= body_id %>" class="<%= body_class %>">

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to APP_CONFIG['app_title'], root_url, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><%= link_to "Home", root_url %></li>
            <li class="active"><%= link_to "Repos", repos_url %></li>
            <li class="active"><%= link_to "SSH Keys", sshkeys_url %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">

    <%= raw flash_messages %>
    <%= yield %>

    <footer class="footer">
      <p class="pull-right"><a href="#">Back to top</a></p>
    </footer>

  </div>
  
</body>
</html>